### ISSUE TITLE
You're not on the leaderboard

### ISSUE THREAD

**Issue by autra** [elemoine/adventofcode#1]
# Description

You're not on the leaderboard of advent of code

# Steps to reproduce the issue

- Turn on your computer
- start your favorite web browser (modern version of firefox or chrome preferred)
- visit https://adventofcode.com/2019/leaderboard

## expected

@elemoine is listed somewhere on the leaderboard, preferrably on first place.

## actual

No @elemoine on leaderboard :sob: 

# Proposal to fix the issue

- @elemoine could work harder
- we could somehow disturb the other participants? But how? Killing all of them doesn't seem doable in practice. How about just threatening them? Do we have a mapping username -> physical address somewhere?
- hack into website
- use photoshop or preferably gimp to fake a leaderboard position and then post it here? It's a bit of a hack, but maybe it's enough to close this? We could revisit this later (for AoC 2020 for instance).

Proposal 1 is my favorite, mainly because it doesn't require any work on my part.

# Additional info

ctrl+f can help to search for username on the leaderboard page.

# Disclaimer

This is of course for satirical purpose and should not be taken seriously.

**Comment by autra** [comment]
Actually, I still have a doubt. Is it really a bug? Or maybe I'm just jealous because I have only 2 stars, and I won't be able to catch up? WDYT?

**Comment by elemoine** [comment]
Wontfix :-)
